env: reactive-v0
env_config:
  simulation: TODO
  movements: TODO
  interactions: TODO
  attributes: TODO
  normalized_attributes: TODO
  agent_speed: int
  deterministic: bool = False
  initial_agent_pos: List[int] = [15, 15]
  randomize_initial_agent_pos: bool = False