area:
  screen_size: 16
  pixel_scale: 50

display:
  fire_size: 1
  control_line_size: 1
  agent_size: 1

simulation:
  update_rate: 1
  runtime: 24hr
  headless: True
  record: false
  save_data: false
  draw_spread_graph: false
  data_type: "npy"
  save_path: "./outputs/gifs/"

mitigation:
  ros_attenuation: True

operational:
  seed:
  latitude: 39.67
  longitude: 119.8
  height: 4000
  width: 4000
  resolution: 30

terrain:
  topography:
    type: functional
    functional:
      function: flat
      perlin:
        octaves: 3
        persistence: 0.7
        lacunarity: 2.0
        seed: 827
        range_min: 100.0
        range_max: 300.0
      gaussian:
        amplitude: 500
        mu_x: 50
        mu_y: 50
        sigma_x: 50
        sigma_y: 50
  fuel:
    type: functional
    functional:
      function: chaparral
      chaparral:
        seed: 1113

fire:
  fire_initial_position:
    type: static
    static:
      position: (0, 0)
    random:
      seed: 1234
  max_fire_duration: 4

environment:
  moisture: 0.03

wind:
  function: simple
  cfd:
    time_to_train: 1000
    iterations: 1
    scale: 1
    timestep_dt: 1.0
    diffusion: 0.0
    viscosity: 0.0000001
    speed: 19
    direction: north
  simple:
    speed: 1
    direction: 135.0
  perlin:
    speed:
      seed: 2345
      scale: 400
      octaves: 3
      persistence: 0.7
      lacunarity: 2.0
      min: 7
      max: 47
    direction:
      seed: 650
      scale: 1500
      octaves: 2
      persistence: 0.9
      lacunarity: 1.0
      min: 0.0
      max: 360.0
