name: sh2
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9.*
  - mamba
  - pip # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.*
  # - tensorflow=2.11.0
  # - tensorflow-probability=0.19.0
  - pytorch::pytorch=1.13.0
  - pytorch::torchvision=0.14.0
  - pytorch::pytorch-cuda=11.6
  - ray-rllib=2.3.0

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
