defaults:
  - environment: environment
  - rollouts: rollouts
  - training: simfire
  - exploration: exploration
  - resources: resources
  - sim_harness: reactive
  - evaluation: evaluation
  - _self_
cli:
  train: False
  view: False
algo:
  name: DQN
stop_conditions:
  iterations: 5
  timesteps: 500000
  ep_mean_rew: 100
model_save:
  trial_name: testing
  save_dir: /home/atapley/fireline/simharness2/ckpts/
  checkpoint_freq: 3
model_load:
  load_path: /home/atapley/fireline/simharness2/ckpts/testing/checkpoint_000005