sim:
  _target_: simfire.sim.simulation.FireSimulation
  config:
    _target_: simfire.utils.config.Config
    config_dict: ${simulation.train}

movements: [none, up, down, left, right]
interactions: [none, fireline]
attributes: [fire_map, elevation, w_0, sigma, delta, M_x]
normalized_attributes: [elevation]
# For now, assume that agent speed is the same for all agents.
agent_speed: 4
num_agents: 3
agent_initialization_method: manual
initial_agent_positions: [[0, 64], [127, 64], [64, 127]]

# Defines the class that will be used to monitor and track `ReactiveHarness`.
harness_analytics_partial:
  _target_: simharness2.analytics.harness_analytics.ReactiveHarnessAnalytics
  _partial_: true
  # Defines the class that will be used to monitor and track `FireSimulation`.
  sim_analytics_partial:
    _target_: simharness2.analytics.simulation_analytics.FireSimulationAnalytics
    _partial_: true
    # Defines the class that will be used to monitor and track agent behavior.
    agent_analytics_partial:
      _target_: simharness2.analytics.agent_analytics.ReactiveAgentAnalytics
      _partial_: true
      movement_types: ${....movements}
      interaction_types: ${....interactions}
# Defines the class that will be used to perform reward calculation at each timestep.
reward_cls_partial:
  _target_: simharness2.rewards.base_reward.SimpleReward
  _partial_: true

action_space_cls:
  _target_: hydra.utils.get_class
  path: gymnasium.spaces.Discrete
