sim:
  _target_: simfire.sim.simulation.FireSimulation
  config:
    _target_: simfire.utils.config.Config
    config_dict: ${simulation.train}
movements: [none, up, down, left, right]
interactions: [none, fireline]
attributes: [fire_map, elevation, w_0, sigma, delta, M_x]
normalized_attributes: [elevation]
agent_speed: 9
initial_agent_pos: [50, 50]
randomize_initial_agent_pos: false
benchmark_sim: ${.sim}
# TODO: Provide higher level option to specify use_benchmark_sim, etc. (??)
# NOTE: To disable usage of `benchmark_sim`, set value to `null` (below).
# benchmark_sim: null
action_space_partial:
  _partial_: true
  _target_: gymnasium.spaces.Discrete
