name: sh2
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - poetry=1.3.*
  - pytorch/linux-64::pytorch=1.13.0 py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch/linux-64::torchvision=0.14.0 py39_cu116
  - pytorch/noarch::pytorch-cuda=11.6 h867d48c_1
  - conda-forge/linux-64::ray-rllib=2.3.0
  - nvidia/linux-64::cuda=11.6.1
  - nvidia/linux-64::cuda-runtime=11.6.1
  - nvidia/linux-64::cuda-toolkit=11.6.1
  - nvidia/linux-64::cuda=11.6.1
# cuda-cccl                 11.6.55              hf6102b2_0    nvidia
# cuda-command-line-tools   11.6.2                        0    nvidia
# cuda-compiler             11.6.2                        0    nvidia
# cuda-cudart               11.6.55              he381448_0    nvidia
# cuda-cudart-dev           11.6.55              h42ad0f4_0    nvidia
# cuda-cuobjdump            11.6.124             h2eeebcb_0    nvidia
# cuda-cupti                11.6.124             h86345e5_0    nvidia
# cuda-cuxxfilt             11.6.124             hecbf4f6_0    nvidia
# cuda-driver-dev           11.6.55                       0    nvidia
# cuda-gdb                  12.1.105                      0    nvidia
# cuda-libraries            11.6.1                        0    nvidia
# cuda-libraries-dev        11.6.1                        0    nvidia
# cuda-memcheck             11.8.86                       0    nvidia
# cuda-nsight               12.1.105                      0    nvidia
# cuda-nsight-compute       12.1.1                        0    nvidia
# cuda-nvcc                 11.6.124             hbba6d2d_0    nvidia
# cuda-nvdisasm             12.1.105                      0    nvidia
# cuda-nvml-dev             11.6.55              haa9ef22_0    nvidia
# cuda-nvprof               12.1.105                      0    nvidia
# cuda-nvprune              11.6.124             he22ec0a_0    nvidia
# cuda-nvrtc                11.6.124             h020bade_0    nvidia
# cuda-nvrtc-dev            11.6.124             h249d397_0    nvidia
# cuda-nvtx                 11.6.124             h0630a44_0    nvidia
# cuda-nvvp                 12.1.105                      0    nvidia
# cuda-runtime              11.6.1                        0    nvidia
# cuda-samples              11.6.101             h8efea70_0    nvidia
# cuda-sanitizer-api        12.1.105                      0    nvidia
# cuda-toolkit              11.6.1                        0    nvidia
# cuda-tools                11.6.1                        0    nvidia
# cuda-version              12.0                 hffde075_0    conda-forge
# cuda-visual-tools         11.6.1                        0    nvidia
