name: sh2-lock
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9.*
  - mamba
  - pip # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.*
  - pytorch/linux-64::pytorch=1.13.0 py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch/linux-64::torchvision=0.14.0 py39_cu116
  - pytorch/noarch::pytorch-cuda=11.6 h867d48c_1
  - conda-forge/linux-64::ray-rllib=2.3.0
  - nvidia/linux-64::cuda=11.6.1
  - nvidia/linux-64::cuda-runtime=11.6.1
  - nvidia/linux-64::cuda-toolkit=11.6.1
  - nvidia/linux-64::cuda=11.6.1

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
